# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  gui_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Install dotnet project dependencies
        run: cd TechEaseSolutions-test && dotnet restore
      - name: Build frontend
        run: cd TechEaseSolutions-test/client && npm install && npm run build
      - name: Build/Restore Playwright Project
        run: cd PlaywrightTests && dotnet build
      - name: Ensure browsers are installed
        run: cd PlaywrightTests && pwsh bin/Debug/net8.0/playwright.ps1 install --with-deps
      - name: Start server
        run: cd TechEaseSolutions-test/server && nohup dotnet run &
      - name: Wait for server to be ready
        run: |
          until curl -sSf http://localhost:5000 > /dev/null; do
          echo "Waiting for server..."
          sleep 2
           done
      - name: Run GUI-tests
        run: cd PlaywrightTests && dotnet test


